/* channels.js — Coub.xyz Channel Catalog
   All channels are free-to-air, public domain, or official broadcaster streams.
   Sources: IPTV-org public catalog, official broadcaster embeds, public domain streams.
*/

const CHANNELS = [
  // ── NEWS ──────────────────────────────────────────────────
  {
    id: "aljazeera-en",
    name: "Al Jazeera English",
    category: "News",
    country: "Qatar",
    countryCode: "QA",
    language: "English",
    logo: "🌍",
    description: "Award-winning global news network broadcasting live from Doha, Qatar.",
    streamUrl: "https://live-hls-web-aje.getaj.net/AJE/index.m3u8",
    embedUrl: "https://www.aljazeera.com/live/",
    website: "https://www.aljazeera.com",
    isLive: true,
    isFeatured: true,
    tags: ["international", "arabic", "english", "politics"]
  },
  {
    id: "dw-en",
    name: "DW News",
    category: "News",
    country: "Germany",
    countryCode: "DE",
    language: "English",
    logo: "🇩🇪",
    description: "Germany's international broadcaster. News, analysis, and documentaries.",
    streamUrl: "https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8",
    embedUrl: "https://www.dw.com/en/media-center/live-tv/s-100825",
    website: "https://www.dw.com",
    isLive: true,
    isFeatured: true,
    tags: ["germany", "europe", "international"]
  },
  {
    id: "france24-en",
    name: "France 24",
    category: "News",
    country: "France",
    countryCode: "FR",
    language: "English",
    logo: "🇫🇷",
    description: "French international news channel broadcasting in English, French, Arabic, and Spanish.",
    streamUrl: "https://stream.france24.com/hls/live/2037092/F24_EN_HI_HLS/master.m3u8",
    embedUrl: "https://www.france24.com/en/live-news/",
    website: "https://www.france24.com",
    isLive: true,
    isFeatured: false,
    tags: ["france", "europe", "multilingual"]
  },
  {
    id: "rt-en",
    name: "RT International",
    category: "News",
    country: "Russia",
    countryCode: "RU",
    language: "English",
    logo: "🌐",
    description: "International news channel offering alternative perspectives on global events.",
    streamUrl: "https://rt-glb.rttv.com/live/rten/playlist.m3u8",
    embedUrl: "https://www.rt.com/on-air/",
    website: "https://www.rt.com",
    isLive: true,
    isFeatured: false,
    tags: ["russia", "international", "alternative"]
  },
  {
    id: "cgtn",
    name: "CGTN",
    category: "News",
    country: "China",
    countryCode: "CN",
    language: "English",
    logo: "🇨🇳",
    description: "China Global Television Network — China's international news broadcaster.",
    streamUrl: "https://news.cgtn.com/resource/blueshift/themes/new-theme/public/resource/hls/cgtn-english.m3u8",
    embedUrl: "https://www.cgtn.com/live",
    website: "https://www.cgtn.com",
    isLive: true,
    isFeatured: false,
    tags: ["china", "asia", "international"]
  },
  {
    id: "trt-world",
    name: "TRT World",
    category: "News",
    country: "Turkey",
    countryCode: "TR",
    language: "English",
    logo: "🇹🇷",
    description: "Turkey's international news broadcaster covering global affairs 24/7.",
    streamUrl: "https://tv-trtworld.medya.trt.com.tr/master.m3u8",
    embedUrl: "https://www.trtworld.com/live",
    website: "https://www.trtworld.com",
    isLive: true,
    isFeatured: false,
    tags: ["turkey", "middle-east", "international"]
  },
  {
    id: "abc-australia",
    name: "ABC Australia",
    category: "News",
    country: "Australia",
    countryCode: "AU",
    language: "English",
    logo: "🇦🇺",
    description: "Australia's national public broadcaster — news, current affairs, and entertainment.",
    streamUrl: "https://abc-iview-ios-live.akamaized.net/stream/hls/abcnews/master.m3u8",
    embedUrl: "https://www.abc.net.au/news/news-bulletin/",
    website: "https://www.abc.net.au",
    isLive: true,
    isFeatured: false,
    tags: ["australia", "public", "english"]
  },

  // ── SPORTS ────────────────────────────────────────────────
  {
    id: "olympic-channel",
    name: "Olympic Channel",
    category: "Sports",
    country: "International",
    countryCode: "INT",
    language: "English",
    logo: "🏅",
    description: "Official Olympic Channel — home of the Olympic Games and sports content.",
    streamUrl: "",
    embedUrl: "https://www.olympicchannel.com/en/live/",
    website: "https://www.olympicchannel.com",
    isLive: true,
    isFeatured: true,
    tags: ["olympics", "athletics", "international"]
  },
  {
    id: "eurosport",
    name: "Eurosport",
    category: "Sports",
    country: "Europe",
    countryCode: "EU",
    language: "English",
    logo: "⚽",
    description: "Pan-European sports channel with free highlights and select live events.",
    streamUrl: "",
    embedUrl: "https://www.eurosport.com/",
    website: "https://www.eurosport.com",
    isLive: false,
    isFeatured: true,
    tags: ["football", "tennis", "cycling", "europe"]
  },
  {
    id: "bbc-sport",
    name: "BBC Sport",
    category: "Sports",
    country: "UK",
    countryCode: "GB",
    language: "English",
    logo: "🏆",
    description: "BBC Sport coverage — free highlights and public event streams from the BBC.",
    streamUrl: "",
    embedUrl: "https://www.bbc.com/sport",
    website: "https://www.bbc.com/sport",
    isLive: false,
    isFeatured: false,
    tags: ["uk", "football", "cricket", "rugby"]
  },
  {
    id: "afl-live",
    name: "AFL Live",
    category: "Sports",
    country: "Australia",
    countryCode: "AU",
    language: "English",
    logo: "🏉",
    description: "Australian Football League official free stream highlights.",
    streamUrl: "",
    embedUrl: "https://www.afl.com.au/watch",
    website: "https://www.afl.com.au",
    isLive: false,
    isFeatured: false,
    tags: ["australia", "AFL", "football"]
  },
  {
    id: "nba-league",
    name: "NBA League Pass Free",
    category: "Sports",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "🏀",
    description: "NBA free preview games and highlights from the official NBA platform.",
    streamUrl: "",
    embedUrl: "https://www.nba.com/watch",
    website: "https://www.nba.com",
    isLive: false,
    isFeatured: false,
    tags: ["basketball", "USA", "NBA"]
  },

  // ── ENTERTAINMENT ─────────────────────────────────────────
  {
    id: "pluto-tv-entertainment",
    name: "Pluto TV Movies",
    category: "Entertainment",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "🎬",
    description: "Free ad-supported streaming TV — classic movies and entertainment 24/7.",
    streamUrl: "",
    embedUrl: "https://pluto.tv/live-tv/pluto-tv-movies",
    website: "https://pluto.tv",
    isLive: true,
    isFeatured: true,
    tags: ["movies", "free", "USA", "entertainment"]
  },
  {
    id: "plex-tv-drama",
    name: "Plex Drama",
    category: "Entertainment",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "🎭",
    description: "Plex free live TV — drama channel available without subscription.",
    streamUrl: "",
    embedUrl: "https://www.plex.tv/live-tv/",
    website: "https://www.plex.tv",
    isLive: true,
    isFeatured: false,
    tags: ["drama", "USA", "free", "entertainment"]
  },
  {
    id: "rakuten-tv",
    name: "Rakuten TV Free",
    category: "Entertainment",
    country: "Europe",
    countryCode: "EU",
    language: "English",
    logo: "🎥",
    description: "Rakuten's free movies and TV channel available across Europe.",
    streamUrl: "",
    embedUrl: "https://rakuten.tv/",
    website: "https://rakuten.tv",
    isLive: true,
    isFeatured: false,
    tags: ["movies", "europe", "free"]
  },

  // ── KIDS ──────────────────────────────────────────────────
  {
    id: "cartoonito",
    name: "Cartoonito Free",
    category: "Kids",
    country: "UK",
    countryCode: "GB",
    language: "English",
    logo: "🧸",
    description: "Free kids' cartoons and educational shows for young children.",
    streamUrl: "",
    embedUrl: "https://www.cartoonito.co.uk/",
    website: "https://www.cartoonito.co.uk",
    isLive: false,
    isFeatured: true,
    tags: ["kids", "cartoons", "education", "uk"]
  },
  {
    id: "pbs-kids",
    name: "PBS Kids 24/7",
    category: "Kids",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "📺",
    description: "PBS Kids free 24/7 live stream — educational programming for children.",
    streamUrl: "https://d2e1asnsl7br7b.cloudfront.net/7782e20e49034254a448d7f337e09fd9/index.m3u8",
    embedUrl: "https://www.pbs.org/parents/",
    website: "https://pbskids.org",
    isLive: true,
    isFeatured: true,
    tags: ["PBS", "USA", "educational", "free", "public"]
  },
  {
    id: "watchabc-kids",
    name: "ABC Kids (Australia)",
    category: "Kids",
    country: "Australia",
    countryCode: "AU",
    language: "English",
    logo: "🐨",
    description: "ABC Kids — Australia's free public broadcaster channel for children.",
    streamUrl: "",
    embedUrl: "https://iview.abc.net.au/channel/abc_kids",
    website: "https://www.abc.net.au/abckids",
    isLive: true,
    isFeatured: false,
    tags: ["australia", "kids", "public", "free"]
  },

  // ── MUSIC ─────────────────────────────────────────────────
  {
    id: "nasa-tv",
    name: "NASA TV",
    category: "Education",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "🚀",
    description: "Live NASA TV — ISS footage, launches, press conferences, and space exploration.",
    streamUrl: "https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8",
    embedUrl: "https://www.nasa.gov/live",
    website: "https://www.nasa.gov",
    isLive: true,
    isFeatured: true,
    tags: ["space", "science", "USA", "public", "free"]
  },
  {
    id: "lofi-hip-hop",
    name: "Lofi Hip Hop Radio",
    category: "Music",
    country: "International",
    countryCode: "INT",
    language: "Instrumental",
    logo: "🎵",
    description: "24/7 lofi hip hop beats to relax and study — official ChilledCow stream.",
    streamUrl: "",
    embedUrl: "https://www.youtube.com/embed/jfKfPfyJRdk?autoplay=1",
    website: "https://www.youtube.com/@LofiGirl",
    isLive: true,
    isFeatured: true,
    tags: ["lofi", "chill", "study", "music"]
  },
  {
    id: "jazz-grooves",
    name: "Jazz Grooves",
    category: "Music",
    country: "USA",
    countryCode: "US",
    language: "Instrumental",
    logo: "🎷",
    description: "Classic and contemporary jazz — a public radio jazz station stream.",
    streamUrl: "",
    embedUrl: "https://www.kcsm.org/listen",
    website: "https://www.kcsm.org",
    isLive: true,
    isFeatured: false,
    tags: ["jazz", "radio", "music", "USA"]
  },
  {
    id: "classical-music",
    name: "ClassicFM Live",
    category: "Music",
    country: "UK",
    countryCode: "GB",
    language: "English",
    logo: "🎻",
    description: "Classical FM — the world's most popular classical music radio station, streamed live.",
    streamUrl: "",
    embedUrl: "https://www.classicfm.com/radio/",
    website: "https://www.classicfm.com",
    isLive: true,
    isFeatured: false,
    tags: ["classical", "orchestra", "uk", "radio"]
  },

  // ── EDUCATION ─────────────────────────────────────────────
  {
    id: "ted-talks",
    name: "TED Talks Live",
    category: "Education",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "💡",
    description: "TED Talks — ideas worth spreading. Free live events and curated talks.",
    streamUrl: "",
    embedUrl: "https://www.ted.com/talks",
    website: "https://www.ted.com",
    isLive: false,
    isFeatured: true,
    tags: ["talks", "science", "technology", "education"]
  },
  {
    id: "cspan",
    name: "C-SPAN",
    category: "Education",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "🏛️",
    description: "Free public affairs network covering US Congress and government proceedings.",
    streamUrl: "https://cspan.akamaized.net/hls/live/2019072/CSPAN1_STREAM_HLS/master.m3u8",
    embedUrl: "https://www.c-span.org/live/",
    website: "https://www.c-span.org",
    isLive: true,
    isFeatured: false,
    tags: ["politics", "USA", "government", "public"]
  },
  {
    id: "euronews-en",
    name: "Euronews",
    category: "News",
    country: "Europe",
    countryCode: "EU",
    language: "English",
    logo: "🇪🇺",
    description: "European news channel covering global stories from a European perspective.",
    streamUrl: "https://rakuten-euronews-1-eu.samsung.wurl.tv/manifest/playlist.m3u8",
    embedUrl: "https://www.euronews.com/live",
    website: "https://www.euronews.com",
    isLive: true,
    isFeatured: false,
    tags: ["europe", "news", "multilingual"]
  },

  // ── DOCUMENTARY ───────────────────────────────────────────
  {
    id: "nat-geo-wild",
    name: "NatGeo Wild (Free)",
    category: "Documentary",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "🦁",
    description: "National Geographic Wild — nature and wildlife documentaries, free clips and streams.",
    streamUrl: "",
    embedUrl: "https://www.nationalgeographic.com/tv/",
    website: "https://www.nationalgeographic.com",
    isLive: false,
    isFeatured: true,
    tags: ["wildlife", "nature", "documentary"]
  },
  {
    id: "smithsonian-channel",
    name: "Smithsonian Channel",
    category: "Documentary",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "🏛️",
    description: "History, science, and culture documentaries from the Smithsonian Institution.",
    streamUrl: "",
    embedUrl: "https://www.smithsonianchannel.com/",
    website: "https://www.smithsonianchannel.com",
    isLive: false,
    isFeatured: false,
    tags: ["history", "science", "culture", "USA"]
  },
  {
    id: "curiosity-stream-free",
    name: "Curiosity Stream Sampler",
    category: "Documentary",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "🔬",
    description: "Free documentary previews from Curiosity Stream — science, history, tech.",
    streamUrl: "",
    embedUrl: "https://curiositystream.com/",
    website: "https://curiositystream.com",
    isLive: false,
    isFeatured: false,
    tags: ["science", "technology", "history"]
  },
  {
    id: "pluto-documentary",
    name: "Pluto TV Documentaries",
    category: "Documentary",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "📽️",
    description: "Free 24/7 documentary channel on Pluto TV — no subscription required.",
    streamUrl: "",
    embedUrl: "https://pluto.tv/live-tv/pluto-tv-documentary",
    website: "https://pluto.tv",
    isLive: true,
    isFeatured: false,
    tags: ["documentary", "free", "USA"]
  },

  // ── ARABIC CHANNELS ───────────────────────────────────────
  {
    id: "aljazeera-ar",
    name: "الجزيرة العربية",
    category: "News",
    country: "Qatar",
    countryCode: "QA",
    language: "Arabic",
    logo: "📡",
    description: "قناة الجزيرة — البث المباشر للأخبار العربية والدولية.",
    streamUrl: "https://live-hls-web-ajaz.getaj.net/AJAZ/index.m3u8",
    embedUrl: "https://www.aljazeera.net/live/",
    website: "https://www.aljazeera.net",
    isLive: true,
    isFeatured: true,
    tags: ["arabic", "news", "middle-east"]
  },
  {
    id: "france24-ar",
    name: "فرانس 24 عربي",
    category: "News",
    country: "France",
    countryCode: "FR",
    language: "Arabic",
    logo: "🇫🇷",
    description: "قناة فرانس 24 العربية — أخبار دولية بالعربية.",
    streamUrl: "https://stream.france24.com/hls/live/2037097/F24_AR_HI_HLS/master.m3u8",
    embedUrl: "https://www.france24.com/ar/بث-مباشر/",
    website: "https://www.france24.com/ar",
    isLive: true,
    isFeatured: false,
    tags: ["arabic", "france", "news"]
  },
  {
    id: "rt-arabic",
    name: "RT Arabic",
    category: "News",
    country: "Russia",
    countryCode: "RU",
    language: "Arabic",
    logo: "📻",
    description: "روسيا اليوم بالعربية — أخبار دولية وتحليلات.",
    streamUrl: "https://rt-arab.rttv.com/live/rtarab/playlist.m3u8",
    embedUrl: "https://arabic.rt.com/on_air/",
    website: "https://arabic.rt.com",
    isLive: true,
    isFeatured: false,
    tags: ["arabic", "russia", "news"]
  },
  {
    id: "mbc-drama",
    name: "MBC Drama",
    category: "Entertainment",
    country: "Saudi Arabia",
    countryCode: "SA",
    language: "Arabic",
    logo: "🎭",
    description: "قناة MBC دراما — أفضل المسلسلات العربية والتركية المدبلجة.",
    streamUrl: "",
    embedUrl: "https://www.mbc.net/ar/mbc-drama",
    website: "https://www.mbc.net",
    isLive: true,
    isFeatured: true,
    tags: ["arabic", "drama", "entertainment", "saudi"]
  },

  // ── SPANISH CHANNELS ──────────────────────────────────────
  {
    id: "rtve-24h",
    name: "RTVE 24h",
    category: "News",
    country: "Spain",
    countryCode: "ES",
    language: "Spanish",
    logo: "🇪🇸",
    description: "Canal 24 Horas de RTVE — noticias en directo de la televisión pública española.",
    streamUrl: "https://ztnr.rtve.es/ztnr/1826237.m3u8",
    embedUrl: "https://www.rtve.es/directo/canal-24h/",
    website: "https://www.rtve.es",
    isLive: true,
    isFeatured: true,
    tags: ["spanish", "spain", "news", "public"]
  },
  {
    id: "cnn-espanol",
    name: "CNN en Español",
    category: "News",
    country: "USA",
    countryCode: "US",
    language: "Spanish",
    logo: "📺",
    description: "CNN en Español — noticias de América Latina y el mundo en español.",
    streamUrl: "",
    embedUrl: "https://cnnespanol.cnn.com/en-vivo/",
    website: "https://cnnespanol.cnn.com",
    isLive: true,
    isFeatured: false,
    tags: ["spanish", "latin-america", "USA", "news"]
  },

  // ── FRENCH CHANNELS ───────────────────────────────────────
  {
    id: "france-info",
    name: "France Info TV",
    category: "News",
    country: "France",
    countryCode: "FR",
    language: "French",
    logo: "🔵",
    description: "France Télévisions — chaîne info en continu, gratuite et publique.",
    streamUrl: "https://simulcast.france.tv/stream/france-info",
    embedUrl: "https://www.francetvinfo.fr/en-direct/tv.html",
    website: "https://www.francetvinfo.fr",
    isLive: true,
    isFeatured: false,
    tags: ["french", "france", "news", "public"]
  },
  {
    id: "tv5monde",
    name: "TV5Monde",
    category: "Entertainment",
    country: "France",
    countryCode: "FR",
    language: "French",
    logo: "🇫🇷",
    description: "TV5Monde — the international French-language television network.",
    streamUrl: "",
    embedUrl: "https://www.tv5monde.com/tv/direct",
    website: "https://www.tv5monde.com",
    isLive: true,
    isFeatured: false,
    tags: ["french", "international", "entertainment"]
  }
];

// ── MATCH SCHEDULES (sample upcoming free events) ─────────
const MATCH_SCHEDULES = [
  { time: "Live", match: "Olympics Athletics Finals", channel: "Olympic Channel", sport: "🏅 Athletics" },
  { time: "18:00", match: "Premier League Highlights", channel: "BBC Sport", sport: "⚽ Football" },
  { time: "20:30", match: "NBA Free Preview Game", channel: "NBA League Pass", sport: "🏀 Basketball" },
  { time: "21:00", match: "Ligue 1 Weekly Digest", channel: "France 24 Sport", sport: "⚽ Football" },
  { time: "Tomorrow", match: "Tour de France Stage", channel: "Eurosport Free", sport: "🚴 Cycling" },
  { time: "Tomorrow", match: "Wimbledon Highlights", channel: "BBC Sport", sport: "🎾 Tennis" },
  { time: "Sun 15:00", match: "AFL Round Highlights", channel: "AFL Live", sport: "🏉 AFL" },
  { time: "Sun 22:00", match: "Formula E Race", channel: "ABB FIA Official", sport: "🏎️ Motorsport" }
];

// ── CATEGORY METADATA ─────────────────────────────────────
const CATEGORIES = [
  { id: "All",           emoji: "📺", label: "All Channels" },
  { id: "News",          emoji: "📰", label: "News" },
  { id: "Sports",        emoji: "🏆", label: "Sports" },
  { id: "Entertainment", emoji: "🎬", label: "Entertainment" },
  { id: "Kids",          emoji: "🧸", label: "Kids" },
  { id: "Music",         emoji: "🎵", label: "Music" },
  { id: "Education",     emoji: "📚", label: "Education" },
  { id: "Documentary",   emoji: "🌍", label: "Documentary" }
];
