/* channels.js — Coub.xyz Channel Catalog
   FIXED: streamUrl = HLS links for native playback via hls.js
          youtubeId  = YouTube live stream ID for embed
          embedUrl   = official iframe-embeddable URL
*/

const CHANNELS = [

  // ── NEWS ─────────────────────────────────────────────────────
  {
    id: "aljazeera-en",
    name: "Al Jazeera English",
    category: "News",
    country: "Qatar",
    countryCode: "QA",
    language: "English",
    logo: "🌍",
    description: "Award-winning global news network broadcasting live from Doha, Qatar.",
    streamUrl: "https://live-hls-web-aje.getaj.net/AJE/index.m3u8",
    youtubeId: "h300dNBtU0o",
    website: "https://www.aljazeera.com",
    isLive: true, isFeatured: true,
    tags: ["international","arabic","english","politics"]
  },
  {
    id: "dw-en",
    name: "DW News",
    category: "News",
    country: "Germany",
    countryCode: "DE",
    language: "English",
    logo: "🇩🇪",
    description: "Germany's international broadcaster — news, analysis, and documentaries.",
    streamUrl: "https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8",
    youtubeId: "mGnFAGOHeFE",
    website: "https://www.dw.com",
    isLive: true, isFeatured: true,
    tags: ["germany","europe","international"]
  },
  {
    id: "france24-en",
    name: "France 24 English",
    category: "News",
    country: "France",
    countryCode: "FR",
    language: "English",
    logo: "🇫🇷",
    description: "French international news channel broadcasting live in English 24/7.",
    streamUrl: "https://stream.france24.com/hls/live/2037092/F24_EN_HI_HLS/master.m3u8",
    youtubeId: "h5to4RqRIrs",
    website: "https://www.france24.com",
    isLive: true, isFeatured: true,
    tags: ["france","europe","multilingual"]
  },
  {
    id: "trt-world",
    name: "TRT World",
    category: "News",
    country: "Turkey",
    countryCode: "TR",
    language: "English",
    logo: "🇹🇷",
    description: "Turkey's international news broadcaster covering global affairs 24/7.",
    streamUrl: "https://tv-trtworld.medya.trt.com.tr/master.m3u8",
    youtubeId: "mMEBTdRFBKo",
    website: "https://www.trtworld.com",
    isLive: true, isFeatured: false,
    tags: ["turkey","middle-east","international"]
  },
  {
    id: "cgtn",
    name: "CGTN",
    category: "News",
    country: "China",
    countryCode: "CN",
    language: "English",
    logo: "🇨🇳",
    description: "China Global Television Network — China's international English news broadcaster.",
    streamUrl: "",
    youtubeId: "FJHxulSaFSU",
    website: "https://www.cgtn.com",
    isLive: true, isFeatured: false,
    tags: ["china","asia","international"]
  },
  {
    id: "euronews-en",
    name: "Euronews",
    category: "News",
    country: "Europe",
    countryCode: "EU",
    language: "English",
    logo: "🇪🇺",
    description: "European news channel covering global stories from a European perspective.",
    streamUrl: "https://rakuten-euronews-1-eu.samsung.wurl.tv/manifest/playlist.m3u8",
    youtubeId: "hZOrQ9iSAqo",
    website: "https://www.euronews.com",
    isLive: true, isFeatured: false,
    tags: ["europe","news","multilingual"]
  },
  {
    id: "abc-australia",
    name: "ABC Australia",
    category: "News",
    country: "Australia",
    countryCode: "AU",
    language: "English",
    logo: "🇦🇺",
    description: "Australia's national public broadcaster — news, current affairs, and entertainment.",
    streamUrl: "",
    youtubeId: "4SpCfzDFBnE",
    website: "https://www.abc.net.au",
    isLive: true, isFeatured: false,
    tags: ["australia","public","english"]
  },
  {
    id: "wion",
    name: "WION",
    category: "News",
    country: "India",
    countryCode: "IN",
    language: "English",
    logo: "🇮🇳",
    description: "World Is One News — India's global news network with live coverage.",
    streamUrl: "",
    youtubeId: "QEsE_KNKQIA",
    website: "https://www.wionews.com",
    isLive: true, isFeatured: false,
    tags: ["india","asia","english","news"]
  },

  // ── ARABIC NEWS ──────────────────────────────────────────────
  {
    id: "aljazeera-ar",
    name: "الجزيرة العربية",
    category: "News",
    country: "Qatar",
    countryCode: "QA",
    language: "Arabic",
    logo: "📡",
    description: "قناة الجزيرة — البث المباشر للأخبار العربية والدولية على مدار الساعة.",
    streamUrl: "https://live-hls-web-ajaz.getaj.net/AJAZ/index.m3u8",
    youtubeId: "CNt5cInp_Vs",
    website: "https://www.aljazeera.net",
    isLive: true, isFeatured: true,
    tags: ["arabic","news","middle-east"]
  },
  {
    id: "france24-ar",
    name: "فرانس 24 عربي",
    category: "News",
    country: "France",
    countryCode: "FR",
    language: "Arabic",
    logo: "📺",
    description: "قناة فرانس 24 العربية — أخبار دولية بالعربية على مدار الساعة.",
    streamUrl: "https://stream.france24.com/hls/live/2037097/F24_AR_HI_HLS/master.m3u8",
    youtubeId: "xu5oBB0v3Qk",
    website: "https://www.france24.com/ar",
    isLive: true, isFeatured: false,
    tags: ["arabic","france","news"]
  },
  {
    id: "rt-arabic",
    name: "RT Arabic",
    category: "News",
    country: "Russia",
    countryCode: "RU",
    language: "Arabic",
    logo: "📻",
    description: "روسيا اليوم بالعربية — أخبار دولية وتحليلات معمّقة.",
    streamUrl: "https://rt-arab.rttv.com/live/rtarab/playlist.m3u8",
    youtubeId: "LvTLGMnNqjY",
    website: "https://arabic.rt.com",
    isLive: true, isFeatured: false,
    tags: ["arabic","russia","news"]
  },

  // ── SPANISH NEWS ─────────────────────────────────────────────
  {
    id: "rtve-24h",
    name: "RTVE Canal 24h",
    category: "News",
    country: "Spain",
    countryCode: "ES",
    language: "Spanish",
    logo: "🇪🇸",
    description: "Canal 24 Horas de RTVE — noticias en directo de la televisión pública española.",
    streamUrl: "https://ztnr.rtve.es/ztnr/1826237.m3u8",
    youtubeId: "5BKMU6OtFP0",
    website: "https://www.rtve.es",
    isLive: true, isFeatured: true,
    tags: ["spanish","spain","news","public"]
  },
  {
    id: "cnn-espanol",
    name: "CNN en Español",
    category: "News",
    country: "USA",
    countryCode: "US",
    language: "Spanish",
    logo: "📺",
    description: "CNN en Español — noticias de América Latina y el mundo las 24 horas.",
    streamUrl: "",
    youtubeId: "0kDkAFuFMsA",
    website: "https://cnnespanol.cnn.com",
    isLive: true, isFeatured: false,
    tags: ["spanish","latin-america","USA","news"]
  },

  // ── FRENCH NEWS ──────────────────────────────────────────────
  {
    id: "france-info",
    name: "France Info TV",
    category: "News",
    country: "France",
    countryCode: "FR",
    language: "French",
    logo: "🔵",
    description: "France Télévisions — chaîne d'info en continu, gratuite et publique.",
    streamUrl: "",
    youtubeId: "wVBxmBYFn3s",
    website: "https://www.francetvinfo.fr",
    isLive: true, isFeatured: false,
    tags: ["french","france","news","public"]
  },

  // ── SPORTS ───────────────────────────────────────────────────
  {
    id: "olympic-channel",
    name: "Olympic Channel",
    category: "Sports",
    country: "International",
    countryCode: "INT",
    language: "English",
    logo: "🏅",
    description: "Official Olympic Channel — home of the Olympic Games, sports news and highlights.",
    streamUrl: "",
    youtubeId: "fnboSRfkWXo",
    website: "https://www.olympicchannel.com",
    isLive: true, isFeatured: true,
    tags: ["olympics","athletics","international"]
  },
  {
    id: "nba-league",
    name: "NBA TV Free",
    category: "Sports",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "🏀",
    description: "NBA free preview games, highlights, and analysis from the official NBA channel.",
    streamUrl: "",
    youtubeId: "cu0CYEcfO5A",
    website: "https://www.nba.com",
    isLive: false, isFeatured: true,
    tags: ["basketball","USA","NBA"]
  },
  {
    id: "nfl-network",
    name: "NFL Network",
    category: "Sports",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "🏈",
    description: "NFL official channel — highlights, analysis, and live game coverage.",
    streamUrl: "",
    youtubeId: "I3E7Oq1wHgA",
    website: "https://www.nfl.com",
    isLive: false, isFeatured: false,
    tags: ["american-football","USA","NFL"]
  },
  {
    id: "formula-e",
    name: "Formula E",
    category: "Sports",
    country: "International",
    countryCode: "INT",
    language: "English",
    logo: "🏎️",
    description: "Official Formula E channel — electric single-seater motorsport races and highlights.",
    streamUrl: "",
    youtubeId: "O6yNh3NKQGM",
    website: "https://www.fiaformulae.com",
    isLive: false, isFeatured: false,
    tags: ["motorsport","formula-e","racing"]
  },

  // ── EDUCATION ────────────────────────────────────────────────
  {
    id: "nasa-tv",
    name: "NASA TV",
    category: "Education",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "🚀",
    description: "Live NASA TV — ISS footage, rocket launches, press conferences, and space exploration.",
    streamUrl: "https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8",
    youtubeId: "nA9UZF-SZoQ",
    website: "https://www.nasa.gov",
    isLive: true, isFeatured: true,
    tags: ["space","science","USA","public","free"]
  },
  {
    id: "cspan",
    name: "C-SPAN",
    category: "Education",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "🏛️",
    description: "Free public affairs network covering US Congress and government proceedings live.",
    streamUrl: "https://cspan.akamaized.net/hls/live/2019072/CSPAN1_STREAM_HLS/master.m3u8",
    youtubeId: "xMxwi5BdaSk",
    website: "https://www.c-span.org",
    isLive: true, isFeatured: false,
    tags: ["politics","USA","government","public"]
  },
  {
    id: "ted-talks",
    name: "TED Talks",
    category: "Education",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "💡",
    description: "TED Talks — ideas worth spreading. Talks on technology, science, global issues.",
    streamUrl: "",
    youtubeId: "Zi9bFsR6fms",
    website: "https://www.ted.com",
    isLive: false, isFeatured: false,
    tags: ["talks","science","technology","education"]
  },

  // ── MUSIC ────────────────────────────────────────────────────
  {
    id: "lofi-hip-hop",
    name: "Lofi Hip Hop Radio",
    category: "Music",
    country: "International",
    countryCode: "INT",
    language: "Instrumental",
    logo: "🎵",
    description: "24/7 lofi hip hop beats to relax and study — the official Lofi Girl stream.",
    streamUrl: "",
    youtubeId: "jfKfPfyJRdk",
    website: "https://www.youtube.com/@LofiGirl",
    isLive: true, isFeatured: true,
    tags: ["lofi","chill","study","music"]
  },
  {
    id: "lofi-jazz",
    name: "Lofi Jazz Radio",
    category: "Music",
    country: "International",
    countryCode: "INT",
    language: "Instrumental",
    logo: "🎷",
    description: "Smooth jazz lofi — relaxing jazz beats streaming live 24/7.",
    streamUrl: "",
    youtubeId: "NEz0yJfKfpE",
    website: "https://www.youtube.com/@LofiGirl",
    isLive: true, isFeatured: false,
    tags: ["jazz","chill","lofi","music"]
  },
  {
    id: "classical-live",
    name: "Classical Music Live",
    category: "Music",
    country: "International",
    countryCode: "INT",
    language: "Instrumental",
    logo: "🎻",
    description: "Live classical music concerts and performances streamed 24/7.",
    streamUrl: "",
    youtubeId: "jYLJwOuRlJw",
    website: "https://www.youtube.com",
    isLive: true, isFeatured: false,
    tags: ["classical","orchestra","live","music"]
  },

  // ── KIDS ─────────────────────────────────────────────────────
  {
    id: "pbs-kids",
    name: "PBS Kids 24/7",
    category: "Kids",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "📺",
    description: "PBS Kids free 24/7 live stream — educational programming for children.",
    streamUrl: "https://d2e1asnsl7br7b.cloudfront.net/7782e20e49034254a448d7f337e09fd9/index.m3u8",
    youtubeId: "dkFRzLxZAbM",
    website: "https://pbskids.org",
    isLive: true, isFeatured: true,
    tags: ["PBS","USA","educational","free","public"]
  },
  {
    id: "kids-cartoons",
    name: "Kids Cartoons TV",
    category: "Kids",
    country: "International",
    countryCode: "INT",
    language: "English",
    logo: "🧸",
    description: "Free cartoon shows and animated movies for kids — available 24/7.",
    streamUrl: "",
    youtubeId: "dkFRzLxZAbM",
    website: "https://www.youtube.com",
    isLive: true, isFeatured: false,
    tags: ["kids","cartoons","animation","free"]
  },

  // ── ENTERTAINMENT ────────────────────────────────────────────
  {
    id: "mbc-drama",
    name: "MBC Drama",
    category: "Entertainment",
    country: "Saudi Arabia",
    countryCode: "SA",
    language: "Arabic",
    logo: "🎭",
    description: "قناة MBC دراما — أفضل المسلسلات العربية والتركية المدبلجة.",
    streamUrl: "",
    youtubeId: "Xp8iyBcj6HQ",
    website: "https://www.mbc.net",
    isLive: true, isFeatured: true,
    tags: ["arabic","drama","entertainment","saudi"]
  },
  {
    id: "comedy-central",
    name: "Comedy TV Live",
    category: "Entertainment",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "😂",
    description: "Stand-up comedy specials and comedy shows streaming live.",
    streamUrl: "",
    youtubeId: "sFnVlQeNEpo",
    website: "https://www.youtube.com",
    isLive: false, isFeatured: false,
    tags: ["comedy","entertainment","USA"]
  },

  // ── DOCUMENTARY ──────────────────────────────────────────────
  {
    id: "free-documentary",
    name: "Free Documentary",
    category: "Documentary",
    country: "International",
    countryCode: "INT",
    language: "English",
    logo: "🎬",
    description: "Full-length free documentaries on nature, history, science, and society.",
    streamUrl: "",
    youtubeId: "2k7fBGBmnRo",
    website: "https://www.youtube.com/@FreeDocumentary",
    isLive: false, isFeatured: true,
    tags: ["documentary","nature","history","free"]
  },
  {
    id: "dw-documentary",
    name: "DW Documentary",
    category: "Documentary",
    country: "Germany",
    countryCode: "DE",
    language: "English",
    logo: "🌍",
    description: "DW Documentary — in-depth reporting on global topics, society, and environment.",
    streamUrl: "",
    youtubeId: "J9VQMNf3Mfs",
    website: "https://www.dw.com/en/documentaries",
    isLive: false, isFeatured: false,
    tags: ["documentary","germany","society","environment"]
  },
  {
    id: "nat-geo-wild",
    name: "Nat Geo Wild",
    category: "Documentary",
    country: "USA",
    countryCode: "US",
    language: "English",
    logo: "🦁",
    description: "National Geographic — nature and wildlife documentaries and live streams.",
    streamUrl: "",
    youtubeId: "rN8KCp8XTPM",
    website: "https://www.nationalgeographic.com",
    isLive: false, isFeatured: false,
    tags: ["wildlife","nature","documentary"]
  }
];

// ── MATCH SCHEDULES ──────────────────────────────────────────
const MATCH_SCHEDULES = [
  { time: "Live",     match: "Olympics Athletics Finals",   channel: "Olympic Channel",  sport: "🏅 Athletics" },
  { time: "18:00",    match: "Premier League Highlights",   channel: "BBC Sport",        sport: "⚽ Football" },
  { time: "20:30",    match: "NBA Free Preview Game",       channel: "NBA TV",           sport: "🏀 Basketball" },
  { time: "21:00",    match: "Ligue 1 Weekly Digest",       channel: "France 24 Sport",  sport: "⚽ Football" },
  { time: "Tomorrow", match: "Tour de France Stage",        channel: "Eurosport Free",   sport: "🚴 Cycling" },
  { time: "Tomorrow", match: "Wimbledon Highlights",        channel: "BBC Sport",        sport: "🎾 Tennis" },
  { time: "Sun 15:00",match: "AFL Round Highlights",        channel: "AFL Live",         sport: "🏉 AFL" },
  { time: "Sun 22:00",match: "Formula E Race",              channel: "Formula E",        sport: "🏎️ Motorsport" }
];

// ── CATEGORIES ───────────────────────────────────────────────
const CATEGORIES = [
  { id: "All",           emoji: "📺", label: "All Channels" },
  { id: "News",          emoji: "📰", label: "News" },
  { id: "Sports",        emoji: "🏆", label: "Sports" },
  { id: "Entertainment", emoji: "🎬", label: "Entertainment" },
  { id: "Kids",          emoji: "🧸", label: "Kids" },
  { id: "Music",         emoji: "🎵", label: "Music" },
  { id: "Education",     emoji: "📚", label: "Education" },
  { id: "Documentary",   emoji: "🌍", label: "Documentary" }
];
